/**
 * VoiceRoom.tsx
 *
 * Connects to a LiveKit room using the livekit-client SDK.
 * End-to-end encryption (E2EE) is enabled via an ExternalE2EEKeyProvider.
 * The encryption key is generated by the Rust backend and never leaves the
 * local machine — it travels only in the URL fragment (# portion), which
 * browsers never send to a server.
 *
 * Encryption is performed inside a Web Worker (livekit-client/e2ee-worker)
 * so that the main thread is never blocked by crypto operations.
 */

import { useEffect, useRef, useState, useCallback } from "react";
import {
  Room,
  RoomEvent,
  Track,
  LocalParticipant,
  RemoteParticipant,
  Participant,
  ExternalE2EEKeyProvider,
  type E2EEOptions,
} from "livekit-client";

interface Props {
  livekitUrl: string;
  token: string;
  e2eeKey: string;
  onLeave: () => void;
}

type ConnectionState = "connecting" | "connected" | "error";

interface ParticipantEntry {
  identity: string;
  isMuted: boolean;
}

export default function VoiceRoom({ livekitUrl, token, e2eeKey, onLeave }: Props) {
  const roomRef = useRef<Room | null>(null);
  const [connState, setConnState] = useState<ConnectionState>("connecting");
  const [muted, setMuted] = useState(false);
  const [participants, setParticipants] = useState<ParticipantEntry[]>([]);
  const [error, setError] = useState<string | null>(null);

  /** Rebuild the participant list from the room snapshot. */
  const refreshParticipants = useCallback((room: Room) => {
    const entries: ParticipantEntry[] = [];

    // Local participant
    const local: LocalParticipant = room.localParticipant;
    const micPub = local.getTrackPublication(Track.Source.Microphone);
    entries.push({
      identity: `${local.identity} (you)`,
      isMuted: micPub?.isMuted ?? true,
    });

    // Remote participants
    room.remoteParticipants.forEach((remote: RemoteParticipant) => {
      const remoteMic = remote.getTrackPublication(Track.Source.Microphone);
      entries.push({
        identity: remote.identity,
        isMuted: remoteMic?.isMuted ?? true,
      });
    });

    setParticipants(entries);
  }, []);

  useEffect(() => {
    let cancelled = false;

    async function connect() {
      try {
        // ------------------------------------------------------------------
        // Build the E2EE key provider.  ExternalE2EEKeyProvider lets us
        // supply an arbitrary passphrase; LiveKit derives an AES-GCM 128-bit
        // key from it via HKDF.
        // ------------------------------------------------------------------
        const keyProvider = new ExternalE2EEKeyProvider();
        // setKey accepts a CryptoKey, ArrayBuffer, or string passphrase.
        await keyProvider.setKey(e2eeKey);

        const e2eeOptions: E2EEOptions = {
          keyProvider,
          // The E2EE worker handles encrypt/decrypt off the main thread.
          worker: new Worker(
            new URL("livekit-client/e2ee-worker", import.meta.url),
            { type: "module" },
          ),
        };

        const room = new Room({ e2ee: e2eeOptions });
        roomRef.current = room;

        // Wire up reactive listeners before connecting.
        room.on(RoomEvent.ParticipantConnected, (_p: Participant) =>
          refreshParticipants(room),
        );
        room.on(RoomEvent.ParticipantDisconnected, (_p: Participant) =>
          refreshParticipants(room),
        );
        room.on(RoomEvent.TrackMuted, () => refreshParticipants(room));
        room.on(RoomEvent.TrackUnmuted, () => refreshParticipants(room));
        room.on(RoomEvent.LocalTrackPublished, () =>
          refreshParticipants(room),
        );
        room.on(RoomEvent.Disconnected, () => {
          if (!cancelled) setConnState("error");
        });

        await room.connect(livekitUrl, token);

        if (cancelled) {
          await room.disconnect();
          return;
        }

        // Publish the local microphone track to the room.  LiveKit will
        // deliver it back to the same participant as a remote track, which
        // is how the loopback audio works in a single-participant session.
        await room.localParticipant.setMicrophoneEnabled(true);

        setConnState("connected");
        refreshParticipants(room);
      } catch (err) {
        if (!cancelled) {
          setError(String(err));
          setConnState("error");
        }
      }
    }

    connect();

    return () => {
      cancelled = true;
      roomRef.current?.disconnect();
      roomRef.current = null;
    };
  }, [livekitUrl, token, e2eeKey, refreshParticipants]);

  async function toggleMute() {
    const room = roomRef.current;
    if (!room) return;
    const nextMuted = !muted;
    await room.localParticipant.setMicrophoneEnabled(!nextMuted);
    setMuted(nextMuted);
    refreshParticipants(room);
  }

  async function handleLeave() {
    await roomRef.current?.disconnect();
    roomRef.current = null;
    onLeave();
  }

  return (
    <div className="card">
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: "12px",
        }}
      >
        <strong>Voice Channel</strong>
        <span
          className={`badge badge--${
            connState === "connected"
              ? "e2ee"
              : connState === "connecting"
                ? "connecting"
                : "disconnected"
          }`}
        >
          {connState === "connected"
            ? "🔗 Connected"
            : connState === "connecting"
              ? "⏳ Connecting…"
              : "✖ Error"}
        </span>
      </div>

      {error && <p className="error-notice">⚠️ {error}</p>}

      {/* Participant list */}
      {participants.length > 0 && (
        <div className="participants">
          {participants.map((p) => (
            <div className="participant-tile" key={p.identity}>
              <span className={`dot ${p.isMuted ? "dot--muted" : ""}`} />
              {p.identity}
              {p.isMuted ? " 🔇" : " 🎙️"}
            </div>
          ))}
        </div>
      )}

      {/* Controls */}
      <div className="controls">
        <button
          className="btn-secondary"
          onClick={toggleMute}
          disabled={connState !== "connected"}
        >
          {muted ? "🎙️ Unmute" : "🔇 Mute"}
        </button>
        <button className="btn-danger" onClick={handleLeave}>
          📵 Leave Room
        </button>
      </div>
    </div>
  );
}
